'use client';
import { useMemo, useState } from 'react';
import { ArrowDown, ArrowLeft, ArrowRight, Bell, Check, ChevronDown, Clock3, Flame, MapPin, Menu, Minus, Plus, Search, ShoppingBag, SlidersHorizontal, Sparkles, Utensils, X } from 'lucide-react';

type Food = { id:number; name:string; desc:string; price:number; tag:string; emoji:string; color:string; sold?:boolean };
type Vendor = { id:number; name:string; area:string; eta:string; rating:string; description:string; initials:string; color:string; foods:Food[] };
const vendors:Vendor[] = [
 {id:1,name:'Mama Nkechi’s Kitchen',area:'Wuse 2 · Abuja',eta:'12–18 min',rating:'4.9',description:'The jollof everyone talks about.',initials:'MN',color:'coral',foods:[{id:1,name:'Party jollof rice',desc:'Smoky, slow-cooked, proper party style.',price:2800,tag:'Bestseller',emoji:'🍚',color:'peach'},{id:2,name:'Ofada rice & ayamase',desc:'Local rice, green pepper sauce, two meats.',price:4200,tag:'Local favourite',emoji:'🍲',color:'sage'},{id:3,name:'Fried plantain',desc:'Sweet, golden and just the right amount.',price:900,tag:'Add-on',emoji:'🍌',color:'yellow'},{id:4,name:'Peppered chicken',desc:'One full leg, grilled then peppered.',price:2600,tag:'Spicy',emoji:'🍗',color:'pink'},{id:5,name:'Moi moi',desc:'Steamed bean pudding, wrapped fresh.',price:1200,tag:'',emoji:'🫔',color:'cream',sold:true}]},
 {id:2,name:'Tunde’s Chop House',area:'Garki · Abuja',eta:'15–22 min',rating:'4.8',description:'Big portions. No long stories.',initials:'TC',color:'green',foods:[{id:6,name:'Egusi & swallow',desc:'Rich ground melon soup with choice of swallow.',price:3500,tag:'Comfort food',emoji:'🥘',color:'sage'},{id:7,name:'Beef suya',desc:'Charcoal-grilled with suya spice.',price:2400,tag:'Popular',emoji:'🍢',color:'peach'}]},
 {id:3,name:'Aunty B’s Rice Pot',area:'Maitama · Abuja',eta:'18–25 min',rating:'4.7',description:'Home food, done with love.',initials:'AB',color:'ochre',foods:[{id:8,name:'Coconut rice',desc:'Creamy coconut rice with grilled fish.',price:3900,tag:'House special',emoji:'🍛',color:'yellow'},{id:9,name:'Beans & dodo',desc:'Soft beans, sweet fried plantain.',price:1800,tag:'',emoji:'🫘',color:'cream'}]}
];
type Cart = Record<number,number>; type Screen='home'|'menu'|'checkout'|'orders';
const money=(n:number)=>'₦'+n.toLocaleString('en-NG');
export default function BukkaGo(){
 const [screen,setScreen]=useState<Screen>('home'); const [vendor,setVendor]=useState<Vendor>(vendors[0]); const [cart,setCart]=useState<Cart>({}); const [query,setQuery]=useState(''); const [filter,setFilter]=useState('All'); const [slot,setSlot]=useState('12:30 – 12:45'); const [orderPlaced,setOrderPlaced]=useState(false); const [orderStatus,setOrderStatus]=useState('Accepted'); const [toast,setToast]=useState(''); const [mobileNav,setMobileNav]=useState(false);
 const cartCount=Object.values(cart).reduce((a,b)=>a+b,0); const total=vendor.foods.reduce((s,f)=>s+f.price*(cart[f.id]||0),0);
 const showToast=(m:string)=>{setToast(m);setTimeout(()=>setToast(''),2100)};
 const add=(id:number)=>setCart(c=>({...c,[id]:(c[id]||0)+1})); const remove=(id:number)=>setCart(c=>{const n={...c}; if(n[id]<=1)delete n[id]; else n[id]--; return n});
 const openVendor=(v:Vendor)=>{if(v.id!==vendor.id&&cartCount>0){setCart({});showToast('Cart cleared for a new spot')}setVendor(v);setScreen('menu');setOrderPlaced(false)};
 const filtered=useMemo(()=>vendors.filter(v=>(v.name.toLowerCase().includes(query.toLowerCase())||v.area.toLowerCase().includes(query.toLowerCase()))&&(filter==='All'||v.area.includes(filter))),[query,filter]);
 const placeOrder=()=>{if(!cartCount)return;setOrderPlaced(true);setOrderStatus('Accepted');setScreen('orders');setCart({});showToast('Order confirmed. See you soon!')};
 return <main className="app-shell">
  <header className="topbar"><div className="topbar-inner"><button className="brand" onClick={()=>setScreen('home')} aria-label="BukkaGo home"><span className="brand-mark"><Utensils size={19}/></span><span>Bukka<span className="brand-go">Go</span><i>.</i></span></button><div className="location-pill"><MapPin size={15}/><span><small>YOU’RE PICKING UP IN</small><b>Wuse 2, Abuja</b></span><ChevronDown size={14}/></div><nav className={mobileNav?'main-nav nav-open':'main-nav'}><button className={screen==='home'||screen==='menu'?'nav-link active':'nav-link'} onClick={()=>setScreen('home')}>Discover</button><button className={screen==='orders'?'nav-link active':'nav-link'} onClick={()=>setScreen('orders')}>Your orders {orderPlaced&&<span className="nav-dot"/>}</button></nav><div className="top-actions"><button className="icon-button notification" onClick={()=>showToast('You’re all caught up')} aria-label="Notifications"><Bell size={19}/><i/></button><button className="profile-button" onClick={()=>showToast('Profile coming soon')}><span className="avatar">J</span><span>Jesam</span><ChevronDown size={14}/></button></div><button className="icon-button mobile-menu" onClick={()=>setMobileNav(!mobileNav)} aria-label="Menu">{mobileNav?<X/>:<Menu/>}</button></div></header>
  {screen==='home'&&<><section className="hero"><div className="hero-inner"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot"/> YOUR LUNCH BREAK, SORTED</div><h1>Good food.<br/><em>Right on time.</em></h1><p>Skip the queue at your favourite bukka.<br className="desktop-only"/> Order ahead, pick up happy.</p><div className="hero-meta"><span><Clock3 size={16}/> Ready in 15–25 mins</span><span className="meta-sep"/><span><MapPin size={16}/> Abuja, FCT</span></div></div><div className="hero-art"><div className="hero-sun"/><div className="hero-plate"><div className="plate-food">🍛</div><span className="plate-leaf">✦</span></div><div className="float-card"><span className="float-icon"><Check size={15}/></span><span><b>Skip the queue</b><small>Your food waits for you</small></span></div><div className="sparkle s1">✳</div><div className="sparkle s2">✦</div></div><div className="hero-note">Made with <span>♥</span> in Naija</div></div></section>
  <section className="discovery"><div className="section-top"><div><div className="eyebrow muted"><Flame size={15}/> THE NEIGHBOURHOOD FAVOURITES</div><h2>What sounds good?</h2><p className="section-sub">Fresh from the pot, ready when you are.</p></div><button className="text-link" onClick={()=>showToast('You’re seeing all open spots')}>See all spots <ArrowRight size={16}/></button></div><div className="search-row"><label className="search-box"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try ‘jollof’, ‘suya’ or a spot name"/><kbd>⌘ K</kbd></label><button className="filter-button" onClick={()=>setFilter(filter==='All'?'Wuse':'All')}><SlidersHorizontal size={17}/><span>{filter==='All'?'Filters':'Wuse 2'}</span><span className="filter-count">{filter==='All'?'2':'×'}</span></button></div><div className="chips"><button className="chip selected" onClick={()=>setFilter('All')}>All spots</button><button className={filter==='Wuse'?'chip selected':'chip'} onClick={()=>setFilter(filter==='Wuse'?'All':'Wuse')}>Around Wuse</button><button className="chip" onClick={()=>showToast('Lunch specials coming up')}>Lunch specials <span>✨</span></button><button className="chip" onClick={()=>showToast('Showing local favourites')}>Local favourites</button></div>
  <div className="vendor-grid">{filtered.map((v,i)=><article className="vendor-card" key={v.id} onClick={()=>openVendor(v)}><div className={'vendor-cover '+v.color}><div className="cover-pattern"/><div className="vendor-monogram">{v.initials}</div><span className="open-badge"><i/> Taking orders</span><div className="food-sticker">{v.foods[0].emoji}</div>{i===0&&<span className="cover-label">FRESH TODAY</span>}</div><div className="vendor-info"><div className="vendor-title"><h3>{v.name}</h3><span className="rating">★ {v.rating}</span></div><p>{v.description}</p><div className="vendor-meta"><span><MapPin size={13}/>{v.area.split(' · ')[0]}</span><span className="meta-dot"/><span><Clock3 size={13}/>{v.eta}</span><span className="pickup-tag">PICKUP</span></div><div className="vendor-bottom"><span className="from-price">From <b>{money(Math.min(...v.foods.map(f=>f.price)))}</b></span><span className="round-arrow"><ArrowRight size={17}/></span></div></div></article>)}</div>{filtered.length===0&&<div className="empty-results"><span>🍽️</span><h3>No spots found just yet</h3><p>Try another search or clear your filters.</p><button className="text-link" onClick={()=>{setQuery('');setFilter('All')}}>Clear search <ArrowRight size={15}/></button></div>}
  <div className="bottom-note"><div className="note-icon"><Sparkles size={18}/></div><span><b>Good things come to those who order ahead.</b><small>Every order helps a local kitchen do what it does best.</small></span><ArrowRight size={18}/></div></section></>}
  {screen==='menu'&&<section className="content-page"><button className="back-link" onClick={()=>setScreen('home')}><ArrowLeft size={16}/> All spots</button><div className="menu-heading"><div className={'menu-avatar '+vendor.color}>{vendor.initials}</div><div><div className="eyebrow muted"><span className="eyebrow-dot"/> OPEN FOR PICKUP</div><h1>{vendor.name}</h1><p>{vendor.description} <span>·</span> <MapPin size={14}/>{vendor.area} <span>·</span> ★ {vendor.rating}</p></div></div><div className="menu-banner"><div><span className="banner-kicker">TODAY’S MENU</span><h2>Cooked fresh.<br/><em>Gone when it’s gone.</em></h2></div><span className="banner-food">{vendor.foods[0].emoji}</span></div><div className="menu-section-title"><div><h2>From the kitchen</h2><p>{vendor.foods.filter(f=>!f.sold).length} dishes available today</p></div><span className="menu-refresh"><span className="eyebrow-dot"/> UPDATING LIVE</span></div><div className="food-list">{vendor.foods.map(f=><article className={f.sold?'food-row unavailable':'food-row'} key={f.id}><div className={'food-thumb '+f.color}><span>{f.emoji}</span></div><div className="food-description">{f.tag&&<span className="food-tag">{f.tag}</span>}<h3>{f.name}</h3><p>{f.desc}</p><b>{money(f.price)}</b></div>{f.sold?<span className="sold-pill">Sold out</span>:<div className="food-controls">{cart[f.id]?<><button onClick={()=>remove(f.id)} aria-label="Remove one"><Minus size={15}/></button><b>{cart[f.id]}</b><button className="add" onClick={()=>add(f.id)} aria-label="Add one"><Plus size={15}/></button></>:<button className="add initial-add" onClick={()=>add(f.id)} aria-label="Add to order"><Plus size={17}/></button>}</div>}</article>)}</div><div className="pickup-info"><Clock3 size={17}/><span><b>Order now, collect in {vendor.eta}</b><small>Choose your pickup time at checkout.</small></span><ArrowRight size={17}/></div></section>}
  {screen==='checkout'&&<section className="content-page checkout-page"><button className="back-link" onClick={()=>setScreen('menu')}><ArrowLeft size={16}/> Back to menu</button><div className="checkout-heading"><div className="eyebrow muted">ALMOST THERE</div><h1>Your pickup, your time.</h1><p>Pick a window that works. We’ll have it ready.</p></div><div className="checkout-grid"><div><div className="checkout-card"><div className="card-title"><span className="step-number">1</span><div><h3>Choose a pickup time</h3><p>{vendor.name} · Today, Tuesday</p></div></div><div className="slot-grid">{['12:15 – 12:30','12:30 – 12:45','12:45 – 1:00','1:00 – 1:15'].map((s,i)=><button key={s} className={slot===s?'slot selected-slot':'slot'} onClick={()=>setSlot(s)}><span>{s}</span><small>{i===0?'2 spots left':i===3?'4 spots left':'Available'}</small>{slot===s&&<Check size={15}/>}</button>)}</div></div><div className="checkout-card"><div className="card-title"><span className="step-number">2</span><div><h3>Your details</h3><p>So the kitchen knows who’s collecting.</p></div></div><div className="input-grid"><label>Your name<input defaultValue="Jesam Obona"/></label><label>Phone number<input defaultValue="+234 801 234 5678"/></label></div></div></div><aside className="summary-card"><div className="summary-vendor"><div className={'summary-avatar '+vendor.color}>{vendor.initials}</div><span><b>{vendor.name}</b><small>Order summary</small></span></div>{vendor.foods.filter(f=>cart[f.id]).map(f=><div className="summary-item" key={f.id}><span className="summary-qty">{cart[f.id]}×</span><span>{f.name}</span><b>{money(f.price*cart[f.id])}</b></div>)}<div className="summary-line"><span>Subtotal</span><b>{money(total)}</b></div><div className="summary-line"><span>Service fee</span><b>{money(150)}</b></div><div className="summary-line total-line"><span>Total</span><b>{money(total+150)}</b></div><button className="primary-button pay-button" onClick={placeOrder}>Preview order tracking <ArrowRight size={17}/></button><p className="secure-note">Preview only · payment is not connected, no charge will be made</p></aside></div></section>}
  {screen==='orders'&&<section className="content-page orders-page"><div className="orders-top"><div><div className="eyebrow muted">YOUR BUKKAGO</div><h1>{orderPlaced?'Nice one, Jesam!':'Your orders'}</h1><p>{orderPlaced?'A local preview of the confirmation screen. This was not submitted.':'All your pickups, in one place.'}</p></div><span className="orders-illustration">🥡</span></div>{orderPlaced?<><div className="order-status-card"><div className="order-confirmed"><div className="confirmed-check"><Check size={21}/></div><span><b>Order preview · not sent to kitchen</b><small>{vendor.name} · Today, {slot} · no payment processed</small></span><span className="live-label"><i/> DEMO</span></div><div className="pickup-code-block"><span>DEMO PICKUP CODE · NOT VALID FOR COLLECTION</span><strong>4 8 2 1 6 3</strong><small>Sample code for interface preview only</small></div><div className="progress-track"><div className="progress-step done"><i><Check size={13}/></i><b>Preview</b></div><div className="progress-line done-line"/><div className={orderStatus==='Preparing'||orderStatus==='Ready'?'progress-step done':'progress-step current'}><i>{orderStatus==='Preparing'||orderStatus==='Ready'?<Check size={13}/>:<span/>}</i><b>Accepted</b></div><div className={orderStatus==='Preparing'||orderStatus==='Ready'?'progress-line done-line':'progress-line'}/><div className={orderStatus==='Ready'?'progress-step done':'progress-step'}><i>{orderStatus==='Ready'?<Check size={13}/>:<span/>}</i><b>Ready</b></div></div><div className="status-message"><span>👩🏾‍🍳</span><p><b>{orderStatus==='Ready'?'Sample status: Ready':orderStatus==='Preparing'?'Sample status: Preparing':'Sample status: Accepted'}</b><small>{orderStatus==='Ready'?'This preview code cannot be used for collection.':'Local preview only. The kitchen has not received this order.'}</small></p></div><div className="order-detail-lines"><div><span>Pickup spot</span><b>{vendor.name}<small>{vendor.area}</small></b></div><div><span>Pickup window</span><b>Today, {slot}</b></div><div><span>Payment</span><b>Not connected · no charge</b></div></div></div><button className="secondary-button simulate" onClick={()=>setOrderStatus(orderStatus==='Accepted'?'Preparing':orderStatus==='Preparing'?'Ready':'Accepted')}><ArrowDown size={15}/> Preview next order update</button></>:<div className="no-orders"><span>🧾</span><h2>No orders yet</h2><p>Your next favourite meal is just around the corner.</p><button className="primary-button" onClick={()=>setScreen('home')}>Find your bukka <ArrowRight size={16}/></button></div>}</section>}
  {cartCount>0&&screen==='menu'&&<div className="cart-dock"><div className="cart-dock-inner"><div className="cart-count"><ShoppingBag size={18}/><span>{cartCount}</span></div><span className="cart-summary"><b>{cartCount} {cartCount===1?'item':'items'}</b><small>Ready in {vendor.eta}</small></span><b className="cart-total">{money(total)}</b><button className="primary-button dock-button" onClick={()=>setScreen('checkout')}>View order <ArrowRight size={16}/></button></div></div>}
  {toast&&<div className="toast"><Check size={17}/>{toast}</div>}
  <footer className="footer"><span className="footer-brand">BukkaGo<span>.</span></span><span>Made for the love of a good meal. <b>© 2026 BukkaGo</b></span><a onClick={()=>showToast('Help is on the way')}>Need a hand?</a></footer>
 </main>
}
