#!/usr/bin/env python3
"""
Seed the Phase 2/3/5/6 admin demo data over the Supabase REST API.

The same orders as supabase/seed-admin-demo.sql, but this environment has no psql and no
database password, so the statements are issued as PostgREST calls with the service role.
The SQL file is the reference for what is being created; this is the transport.

The auth.users rows are the reason this script exists at all: they need the admin API, and
without a vendor owner there is no session that could have tried to self-approve, so the
column-grant fix in migration 003 could not be verified by hand.

Idempotent. Re-running creates nothing new and prints the existing rows.

Usage:  python3 scripts/seed-admin-demo.py
Reads:  app/.env.local  (SUPABASE_SERVICE_ROLE_KEY — never printed)
Warns:  this prints generated passwords to stdout, once.
"""

import json
import os
import pathlib
import re
import secrets
import string
import sys
import urllib.error
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
ENV = ROOT / "app" / ".env.local"

VENDOR_EMAIL = "vendor@bukkago.com"
CUSTOMER_EMAIL = "customer@bukkago.com"
VENDOR_ID = 1  # Mama Nkechi's Kitchen

# (id, vendor name, status, pickup code, total, payment status, created offset)
# Explicit ids do not advance a `generated by default as identity` column, so the
# sequence stays at 1 and the first real place_order() call gets id=1, not 9010. Harmless
# (nothing collides), but the ids read oddly. PostgREST exposes no setval, so this script
# cannot do what the SQL twin does; run the setval there if the numbering matters.
ORDERS = [
    (9001, "Mama Nkechi's Kitchen", "pending",   "482163", 7950,  "paid",     12),
    (9002, "Mama Nkechi's Kitchen", "preparing", "731904", 7700,  "paid",     26),
    (9003, "Tunde's Chop House",    "ready",     "115028", 5500,  "paid",     41),
    (9004, "Tunde's Chop House",    "collected", "640517", 5500,  "paid",     120),
    (9005, "Aunty B's Rice Pot",    "collected", "293846", 11600, "paid",     180),
    (9006, "Aunty B's Rice Pot",    "no_show",   "507319", 7600,  "paid",     300),
    (9007, "Sabi Chop Spot",        "cancelled", "861204", 3200,  "refunded", 420),
    (9008, "Sabi Chop Spot",        "collected", "174635", 5000,  "paid",     1560),
    (9009, "Mama Nkechi's Kitchen", "collected", "928401", 4500,  "unpaid",   1800),
]

ITEMS = [
    (9001, "Jollof rice + chicken", 3500, 1, 3500),
    (9001, "Egusi soup + pounded yam", 4500, 1, 4500),
    (9002, "Fried rice + prawns", 4200, 1, 4200),
    (9002, "Jollof rice + chicken", 3500, 1, 3500),
    (9003, "Chopped rice + egg", 3000, 1, 3000),
    (9003, "Akara + bread + tea", 1800, 1, 1800),
    (9004, "Chopped rice plate", 2500, 1, 2500),
    (9004, "Chopped rice + egg", 3000, 1, 3000),
    (9005, "Jollof + stew + chicken", 3800, 2, 7600),
    (9005, "Egusi + eba", 4200, 1, 4200),
    (9006, "Jollof + stew + chicken", 3800, 2, 7600),
    (9007, "Chopped rice + fish", 3200, 1, 3200),
    (9008, "Akara + bread + tea", 1800, 1, 1800),
    (9008, "Chopped rice + fish", 3200, 1, 3200),
    (9009, "Egusi soup + pounded yam", 4500, 1, 4500),
]

DISPUTES = [
    (9006, "customer", "no_show",
     "Ordered and prepaid, waited 25 minutes past my slot, then left.", "open"),
    (9003, "vendor", "quality",
     "Customer says the fish was undercooked. Photo attached in the app.", "investigating"),
    (9007, "system", "payment",
     "Order was refunded by the vendor but the webhook never confirmed it.", "resolved"),
]

ALPHANUM = string.ascii_letters + string.digits


def read_env() -> dict:
    if not ENV.exists():
        sys.exit(f"error: {ENV} not found. Create it from app/.env.example first.")
    text = ENV.read_text()
    env = dict(re.findall(r"^([A-Z0-9_]+)=(.*)$", text, re.M))
    for key in ("NEXT_PUBLIC_SUPABASE_URL", "SUPABASE_SERVICE_ROLE_KEY"):
        if not env.get(key):
            sys.exit(f"error: {key} missing from {ENV}")
    return env


def make_password() -> str:
    """20 random alphanumerics plus fixed mixed-case/symbol edges."""
    return "Bg!" + "".join(secrets.choice(ALPHANUM) for _ in range(20)) + "#7"


class Client:
    def __init__(self, env: dict):
        self.url = env["NEXT_PUBLIC_SUPABASE_URL"].rstrip("/")
        self.service = env["SUPABASE_SERVICE_ROLE_KEY"]

    def _send(self, url: str, key: str, method: str, body=None, prefer=None, conflict=None):
        headers = {"apikey": key, "Authorization": f"Bearer {key}"}
        data = None
        if body is not None:
            data = json.dumps(body).encode()
            headers["Content-Type"] = "application/json"
        directives = [d for d in (prefer, f"on_conflict={conflict}" if conflict else None) if d]
        if directives:
            headers["Prefer"] = ",".join(directives)
        request = urllib.request.Request(url, data=data, headers=headers, method=method)
        try:
            with urllib.request.urlopen(request, timeout=30) as response:
                raw = response.read().decode()
                return response.status, (json.loads(raw) if raw.strip() else [])
        except urllib.error.HTTPError as error:
            return error.code, error.read().decode()[:300]
        except Exception as error:  # noqa: BLE001 - surface any transport failure
            return "ERR", str(error)[:200]

    def rest(self, table: str, body=None, method="POST", prefer="return=representation",
             conflict: str | None = None):
        """
        Prefer is a header, never a query string. PostgREST parses the query string as a
        filter, so `?return=minimal` is read as a filter on a column called `return` and
        fails with PGRST100. Conflict resolution is also a Prefer value for the same reason.
        """
        return self._send(
            f"{self.url}/rest/v1/{table}", self.service, method, body, prefer, conflict
        )

    def select(self, table: str, params: str = ""):
        url = f"{self.url}/rest/v1/{table}" + (f"?{params}" if params else "")
        status, data = self._send(url, self.service, "GET")
        return data if status == 200 else []

    def auth_admin(self, path: str, body=None, method="POST"):
        return self._send(f"{self.url}/auth/v1/{path}", self.service, method, body)

    def find_user(self, email: str):
        status, data = self.auth_admin(f"admin/users?per_page=200", method="GET")
        if status != 200:
            return None
        for user in (data or {}).get("users", []):
            if user.get("email") == email:
                return user["id"]
        return None

    def ensure_user(self, email: str) -> tuple[str, str | None]:
        """Create the auth user if absent. Returns (uuid, password-or-None)."""
        existing = self.find_user(email)
        if existing:
            print(f"  = {email} already exists ({existing})")
            return existing, None

        password = make_password()
        status, data = self.auth_admin(
            "admin/users",
            {"email": email, "password": password, "email_confirm": True},
        )
        if status not in (200, 201):
            print(f"  ! could not create {email}: {status} {str(data)[:160]}")
            return "", None

        uuid = data.get("id") or data.get("user", {}).get("id")
        print(f"  + {email} created ({uuid})")
        return uuid, password


def insert_if_absent(client: Client, table: str, key: str, value, row: dict, conflict: str) -> bool:
    """Insert one row unless a row with the same key already exists."""
    probe = client.select(table, f"{key}=eq.{value}&limit=1")
    if probe:
        return False
    status, body = client.rest(table, row, conflict=conflict)
    if status not in (200, 201):
        print(f"  ! {table} insert failed: {status} {str(body)[:160]}")
        return False
    return True


def main() -> int:
    env = read_env()
    client = Client(env)

    print("1. identities")
    vendor_uuid, vendor_pw = client.ensure_user(VENDOR_EMAIL)
    customer_uuid, customer_pw = client.ensure_user(CUSTOMER_EMAIL)
    if not vendor_uuid or not customer_uuid:
        print("\nAborting: no auth users, so orders would have no customer to reference.")
        return 1

    print("\n2. roles")
    if insert_if_absent(client, "vendor_accounts", "id", vendor_uuid, {
        "id": vendor_uuid, "vendor_id": VENDOR_ID,
        "display_name": "Nkechi (demo owner)", "role": "owner",
    }, "id"):
        print(f"  + vendor_accounts -> vendor {VENDOR_ID}")
    if insert_if_absent(client, "customers", "id", customer_uuid, {
        "id": customer_uuid, "name": "Demo Customer", "phone": "+234 800 555 0100",
    }, "id"):
        print("  + customers")

    vendors = {v["name"]: v["id"] for v in client.select("vendors", "select=id,name")}
    if "Mama Nkechi's Kitchen" not in vendors:
        print("\nAborting: seed.sql vendors are missing. Run the first seed step first.")
        return 1

    print("\n3. orders")
    now_epoch = int(datetime_now().timestamp())
    existing = {row["id"] for row in client.select("orders", "select=id&id=in.(9001,9002,9003,9004,9005,9006,9007,9008,9009)")}
    batch = []
    for order_id, vendor_name, status, code, total, payment, minutes_ago in ORDERS:
        if order_id in existing:
            continue
        created = iso_from_epoch(now_epoch - minutes_ago * 60)
        accepted = created if status in ("accepted", "preparing", "ready", "collected") else None
        ready = created if status in ("ready", "collected") else None
        collected = created if status == "collected" else None
        cancelled = created if status in ("cancelled", "no_show") else None
        batch.append({
            "id": order_id,
            "customer_id": customer_uuid,
            "vendor_id": vendors[vendor_name],
            "status": status,
            "pickup_code": code,
            "total_amount": total,
            "payment_status": payment,
            "idempotency_key": f"seed-{order_id}",
            "accepted_at": accepted,
            "ready_at": ready,
            "collected_at": collected,
            "cancelled_at": cancelled,
            "created_at": created,
        })
    if batch:
        status, body = client.rest("orders", batch)
        print(f"  + {len(batch)} orders" if status in (200, 201)
              else f"  ! orders failed: {status} {str(body)[:200]}")
    else:
        print("  = orders already present")

    print("\n4. order items")
    have = {row["order_id"] for row in client.select("order_items", "select=order_id&order_id=in.(9001,9002,9003,9004,9005,9006,9007,9008,9009)")}
    item_rows = [
        {
            "order_id": order_id, "name_snapshot": name, "price_snapshot": price,
            "quantity": qty, "subtotal": subtotal,
        }
        for order_id, name, price, qty, subtotal in ITEMS
        if order_id not in have
    ]
    if item_rows:
        status, body = client.rest("order_items", item_rows)
        print(f"  + {len(item_rows)} order items" if status in (200, 201)
              else f"  ! items failed: {status} {str(body)[:200]}")
    else:
        print("  = order items already present")

    print("\n5. payments")
    paid = {row["order_id"] for row in client.select("payments", "select=order_id&order_id=in.(9001,9002,9003,9004,9005,9006,9007,9008,9009)")}
    payment_map = {
        "paid": "success", "refunded": "refunded", "failed": "failed", "unpaid": "pending",
    }
    payment_rows = []
    for order_id, _v, _s, _c, total, payment, minutes_ago in ORDERS:
        if order_id in paid:
            continue
        payment_rows.append({
            "order_id": order_id, "provider": "paystack",
            "provider_reference": f"seed-pay-{order_id}",
            "amount": total, "status": payment_map[payment],
            "created_at": iso_from_epoch(now_epoch - minutes_ago * 60 + 60),
        })
    # One recent failure so the Overview webhook alert has a subject.
    if 9002 not in paid and not any(
        p["provider_reference"] == "seed-pay-fail-9002" for p in payment_rows
    ):
        payment_rows.append({
            "order_id": 9002, "provider": "paystack",
            "provider_reference": "seed-pay-fail-9002", "amount": 7700,
            "status": "failed", "created_at": iso_from_epoch(now_epoch - 90 * 60),
        })
    if payment_rows:
        status, body = client.rest("payments", payment_rows)
        print(f"  + {len(payment_rows)} payments" if status in (200, 201)
              else f"  ! payments failed: {status} {str(body)[:200]}")
    else:
        print("  = payments already present")

    print("\n6. disputes")
    existing_descriptions = {
        row["description"]
        for row in client.select("disputes", "select=description")
    }
    dispute_rows = [
        {
            "order_id": order_id, "raised_by_type": raised_by, "dispute_type": kind,
            "description": description, "status": status,
        }
        for order_id, raised_by, kind, description, status in DISPUTES
        if description not in existing_descriptions
    ]
    if dispute_rows:
        status, body = client.rest("disputes", dispute_rows)
        print(f"  + {len(dispute_rows)} disputes" if status in (200, 201)
              else f"  ! disputes failed: {status} {str(body)[:200]}")
    else:
        print("  = disputes already present")

    print("\n" + "=" * 68)
    if vendor_pw or customer_pw:
        print("NEW PASSWORDS — shown once, not stored anywhere:")
        if vendor_pw:
            print(f"  {VENDOR_EMAIL}    {vendor_pw}")
        if customer_pw:
            print(f"  {CUSTOMER_EMAIL}  {customer_pw}")
        print("=" * 68)
    else:
        print("No new accounts; both identities already existed.")
    print("\nNow verify the migration 003 column grants by signing in as the vendor")
    print(f"owner ({VENDOR_EMAIL}) and running, in the SQL editor:")
    print("  update public.vendors set status = 'active' where id = 1;   -- must fail")
    print("  update public.pickup_slots set orders_count = 0 where vendor_id = 1;  -- must fail")
    print("  update public.vendors set phone = '08000000000' where id = 1;  -- must succeed")
    return 0


def datetime_now():
    import datetime
    return datetime.datetime.now(datetime.timezone.utc)


def iso_from_epoch(epoch: int) -> str:
    import datetime
    return datetime.datetime.fromtimestamp(epoch, datetime.timezone.utc).isoformat()


if __name__ == "__main__":
    sys.exit(main())
