-- Super Admin Panel — schema additions
-- Implements DOCS/09-SUPER-ADMIN-SCHEMA.md §1–§3 with the decisions recorded in
-- DOCS/11-SUPER-ADMIN-DECISIONS.md:
--   §7.1 two-tier roles (super_admin / support_admin)
--   §7.2 RLS blocks all direct writes; sensitive actions go through SECURITY DEFINER
--         functions invoked with the caller's own session so auth.uid() stays intact
--   §7.3 admin authority stops at approve/reject/suspend — menu content stays vendor-owned
--   §7.4 no refund approval threshold (refunds land in Phase 4)

-- ============================================================
-- 1. ALTERATIONS TO EXISTING TABLES
-- ============================================================

alter table public.admin_users
  add column if not exists role text not null default 'support_admin'
    check (role in ('super_admin', 'support_admin'));

alter table public.vendors
  add column if not exists suspended_at timestamptz,
  add column if not exists suspended_reason text,
  add column if not exists suspended_by uuid references public.admin_users(id) on delete set null,
  add column if not exists commission_rate numeric(5,2);

create index if not exists vendors_status_idx on public.vendors (status);

alter table public.customers
  add column if not exists banned_at timestamptz,
  add column if not exists banned_reason text,
  add column if not exists banned_by uuid references public.admin_users(id) on delete set null;

-- ============================================================
-- 2. NEW TABLES
-- ============================================================

create table if not exists public.disputes (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  raised_by_type text not null check (raised_by_type in ('customer', 'vendor', 'system')),
  raised_by_id uuid,
  dispute_type text not null check (dispute_type in ('quality', 'no_show', 'payment', 'other')),
  description text not null,
  status text not null default 'open' check (status in ('open', 'investigating', 'resolved', 'rejected')),
  resolution_notes text,
  resolved_by uuid references public.admin_users(id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists disputes_order_id_idx on public.disputes (order_id);
create index if not exists disputes_status_idx on public.disputes (status);

create table if not exists public.refunds (
  id bigint generated by default as identity primary key,
  -- restrict, not cascade: a refund is a money record and must survive any attempt to
  -- remove the order it refers to. Nothing can delete an order through RLS anyway.
  order_id bigint not null references public.orders(id) on delete restrict,
  payment_id bigint not null references public.payments(id) on delete restrict,
  dispute_id bigint references public.disputes(id) on delete set null,
  amount numeric(10,2) not null check (amount > 0),
  reason text not null check (nullif(trim(reason), '') is not null),
  status text not null default 'pending' check (status in ('pending', 'approved', 'processed', 'rejected')),
  requested_by uuid not null references public.admin_users(id) on delete restrict,
  approved_by uuid references public.admin_users(id) on delete set null,
  processor_reference text,
  created_at timestamptz not null default now(),
  processed_at timestamptz
);

create index if not exists refunds_order_id_idx on public.refunds (order_id);
create index if not exists refunds_status_idx on public.refunds (status);

-- Append-only accountability record. See the reject_mutation trigger at the end of
-- this file and the deliberately absent INSERT/UPDATE/DELETE policies below.
create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  admin_id uuid not null references public.admin_users(id) on delete restrict,
  action text not null,
  target_table text not null,
  target_id text not null,
  before_state jsonb,
  after_state jsonb,
  reason text,
  ip_address text,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_log_admin_id_idx on public.admin_audit_log (admin_id);
create index if not exists admin_audit_log_target_idx on public.admin_audit_log (target_table, target_id);
create index if not exists admin_audit_log_created_at_idx on public.admin_audit_log (created_at desc);

create table if not exists public.platform_settings (
  key text primary key,
  value jsonb not null,
  updated_by uuid references public.admin_users(id) on delete set null,
  updated_at timestamptz not null default now()
);

insert into public.platform_settings (key, value) values
  ('default_commission_rate', '5.0'::jsonb),
  ('no_show_grace_period_minutes', '30'::jsonb),
  ('refund_approval_threshold_ngn', 'null'::jsonb)
on conflict (key) do nothing;

-- ============================================================
-- 3. ROLE LEVEL SECURITY
-- ============================================================

alter table public.disputes enable row level security;
alter table public.refunds enable row level security;
alter table public.admin_audit_log enable row level security;
alter table public.platform_settings enable row level security;

-- Decides §7.1. SECURITY DEFINER + stable because it is called from RLS policies, and it
-- has to bypass admin_users RLS or the policy that calls it would recurse. Not referenced
-- by any policy yet: it exists for Phase 5's admin_update_setting(key, value), which will
-- be the only thing allowed to write platform_settings.
create or replace function public.is_super_admin() returns boolean
  language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.admin_users where id = auth.uid() and role = 'super_admin')
$$;

-- Disputes: admins see all; the customer/vendor on the underlying order sees their own.
create policy disputes_read on public.disputes
  for select using (
    public.is_admin()
    or exists (
      select 1 from public.orders o
      where o.id = disputes.order_id
        and (
          o.customer_id = auth.uid()
          or exists (select 1 from public.vendor_accounts va where va.id = auth.uid() and va.vendor_id = o.vendor_id)
        )
    )
  );

-- Refunds: admins see all; the customer/vendor on the underlying order sees their own.
create policy refunds_read on public.refunds
  for select using (
    public.is_admin()
    or exists (
      select 1 from public.orders o
      where o.id = refunds.order_id
        and (
          o.customer_id = auth.uid()
          or exists (select 1 from public.vendor_accounts va where va.id = auth.uid() and va.vendor_id = o.vendor_id)
        )
    )
  );

-- Audit log: every admin can read all of it. There is deliberately no INSERT, UPDATE or
-- DELETE policy — RLS defaults to deny, so no authenticated role can write here at all.
-- Writes happen inside the SECURITY DEFINER functions in section 4.
create policy admin_audit_log_read on public.admin_audit_log
  for select using (public.is_admin());

-- The initial schema only let an admin read their own admin_users row, which is enough to
-- gate the panel but not to render the audit log: spec §3.7 asks for a log of "each
-- admin's recent actions", and attributing a row to a person is the entire point of an
-- accountability record. Read-only, still admin-only. (Also unblocks Phase 5's admin
-- account management.) Permissive policies are OR'd, so admin_self_read still applies.
create policy admin_users_read_admin on public.admin_users
  for select to authenticated using (public.is_admin());

create policy platform_settings_read on public.platform_settings
  for select using (public.is_admin());

-- Deliberately no UPDATE policy. Spec §6 requires a settings change to be logged with its
-- old and new value, and RLS cannot enforce "you may write, but only through code that
-- writes an audit row first". Leaving a super-admin UPDATE policy here would be an
-- unaudited write path to the platform's money and no-show rules. Phase 5 adds
-- admin_update_setting(key, value) as a SECURITY DEFINER function that logs
-- 'settings.update', the same pattern as section 4. Until then, only the service role
-- can change a setting.

-- Known gap for Phase 5: vendors_admin_insert (from the initial schema) still lets any
-- admin create a vendor row directly, with no audit entry. Spec §6's list covers
-- approve/reject/suspend/reactivate rather than creation, so it is left in place for now.

-- §7.2 requires that no authenticated role can change a vendor's status, commission or
-- suspension fields except through an audited function. vendors_manage (initial schema)
-- granted public.is_admin() a direct UPDATE, which would let any admin silently flip
-- vendors.status to 'suspended' and skip the audit log entirely — the exact hole §7.2
-- exists to close. Rebuild it for vendor owners only.
drop policy if exists vendors_manage on public.vendors;
create policy vendors_manage on public.vendors
  for update to authenticated
  using (exists (select 1 from public.vendor_accounts va where va.id = auth.uid() and va.vendor_id = vendors.id and va.role = 'owner'))
  with check (exists (select 1 from public.vendor_accounts va where va.id = auth.uid() and va.vendor_id = vendors.id and va.role = 'owner'));

-- A customer must not be able to clear their own ban. customers_self_update is a
-- table-level UPDATE grant, so RLS alone cannot tell which columns are being written.
-- Column-level privileges are the mechanism Postgres actually offers for this: drop the
-- blanket grant and re-grant only the two columns a customer owns.
revoke update on public.customers from authenticated;
grant update (name, phone) on public.customers to authenticated;

-- §7.3: admin authority stops at approve / reject / suspend. Drop the admin clause that the
-- initial schema granted on menu_items so only a vendor account for that vendor can write.
-- (The initial migration named this policy menu_vendor_manage, not menu_items_write_vendor.)
drop policy if exists menu_vendor_manage on public.menu_items;
create policy menu_vendor_manage on public.menu_items
  for all to authenticated
  using (public.owns_vendor(vendor_id))
  with check (public.owns_vendor(vendor_id));

-- Belt and braces on top of the RLS deny-by-default above: block UPDATE and DELETE on the
-- audit log even for the table owner, so the append-only guarantee is not merely a policy
-- convention. Nothing in the application is expected to ever hit this.
create or replace function public.admin_audit_log_reject_mutation() returns trigger
  language plpgsql as $$
begin
  raise exception 'ADMIN_AUDIT_LOG_APPEND_ONLY';
end;
$$;

drop trigger if exists admin_audit_log_append_only on public.admin_audit_log;
create trigger admin_audit_log_append_only
  before update or delete on public.admin_audit_log
  for each row execute function public.admin_audit_log_reject_mutation();

-- ============================================================
-- 4. AUDITED ADMIN ACTIONS
-- ============================================================
--
-- These are called with the acting admin's own Supabase session (the anon key plus their
-- session cookie), NOT the service-role key. That distinction matters: auth.uid() is
-- derived from the caller's JWT, so the is_admin() check below is evaluated against the
-- real person. Running them with the service role would make auth.uid() null and the
-- check would always fail.
--
-- Each function is SECURITY DEFINER, so as the table owner it bypasses the vendors RLS
-- that deliberately denies authenticated writes. The write and its admin_audit_log row
-- are a single transaction: if the audit insert fails, the write rolls back with it.

create or replace function public.admin_approve_vendor(p_vendor_id bigint, p_reason text default null)
  returns jsonb
  language plpgsql security definer set search_path = public as $$
declare
  v_admin uuid := auth.uid();
  v_vendor public.vendors%rowtype;
begin
  if v_admin is null or not public.is_admin() then
    raise exception 'FORBIDDEN';
  end if;
  if nullif(trim(coalesce(p_reason, '')), '') is null then
    raise exception 'REASON_REQUIRED';
  end if;

  select * into v_vendor from public.vendors where id = p_vendor_id for update;
  if not found then
    raise exception 'VENDOR_NOT_FOUND';
  end if;
  if v_vendor.status <> 'pending' then
    raise exception 'VENDOR_NOT_PENDING';
  end if;

  update public.vendors
    set status = 'active', suspended_at = null, suspended_reason = null, suspended_by = null
    where id = p_vendor_id;

  insert into public.admin_audit_log (admin_id, action, target_table, target_id, before_state, after_state, reason)
  values (
    v_admin,
    'vendor.approve',
    'vendors',
    p_vendor_id::text,
    jsonb_build_object('status', v_vendor.status, 'name', v_vendor.name),
    jsonb_build_object('status', 'active', 'name', v_vendor.name),
    trim(p_reason)
  );

  return jsonb_build_object('id', p_vendor_id, 'status', 'active', 'name', v_vendor.name);
end;
$$;

create or replace function public.admin_reject_vendor(p_vendor_id bigint, p_reason text)
  returns jsonb
  language plpgsql security definer set search_path = public as $$
declare
  v_admin uuid := auth.uid();
  v_vendor public.vendors%rowtype;
begin
  if v_admin is null or not public.is_admin() then
    raise exception 'FORBIDDEN';
  end if;
  if nullif(trim(coalesce(p_reason, '')), '') is null then
    raise exception 'REASON_REQUIRED';
  end if;

  select * into v_vendor from public.vendors where id = p_vendor_id for update;
  if not found then
    raise exception 'VENDOR_NOT_FOUND';
  end if;
  if v_vendor.status <> 'pending' then
    raise exception 'VENDOR_NOT_PENDING';
  end if;

  update public.vendors set status = 'rejected' where id = p_vendor_id;

  insert into public.admin_audit_log (admin_id, action, target_table, target_id, before_state, after_state, reason)
  values (
    v_admin,
    'vendor.reject',
    'vendors',
    p_vendor_id::text,
    jsonb_build_object('status', v_vendor.status, 'name', v_vendor.name),
    jsonb_build_object('status', 'rejected', 'name', v_vendor.name),
    trim(p_reason)
  );

  return jsonb_build_object('id', p_vendor_id, 'status', 'rejected', 'name', v_vendor.name);
end;
$$;

revoke all on function public.admin_approve_vendor(bigint, text) from public, anon;
grant execute on function public.admin_approve_vendor(bigint, text) to authenticated;
revoke all on function public.admin_reject_vendor(bigint, text) from public, anon;
grant execute on function public.admin_reject_vendor(bigint, text) to authenticated;
