-- BukkaGo v1 schema. Run with Supabase CLI: supabase db push
create extension if not exists pgcrypto;

create table if not exists public.vendors (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  logo_url text,
  area text,
  address text,
  phone text,
  avg_prep_time_minutes integer not null default 15 check (avg_prep_time_minutes > 0),
  status text not null default 'pending' check (status in ('pending','active','suspended','rejected')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.admin_users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  created_at timestamptz not null default now()
);
create table if not exists public.vendor_accounts (
  id uuid primary key references auth.users(id) on delete cascade,
  vendor_id bigint not null references public.vendors(id) on delete cascade,
  display_name text,
  role text not null default 'owner' check (role in ('owner','staff')),
  created_at timestamptz not null default now()
);
create index if not exists vendor_accounts_vendor_idx on public.vendor_accounts(vendor_id);
create table if not exists public.customers (
  id uuid primary key references auth.users(id) on delete cascade,
  name text, phone text, created_at timestamptz not null default now()
);
create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  vendor_id bigint not null references public.vendors(id) on delete cascade,
  name text not null, description text, photo_url text,
  price numeric(10,2) not null check(price >= 0),
  quantity_remaining integer check(quantity_remaining is null or quantity_remaining >= 0),
  is_available boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists menu_items_vendor_available_idx on public.menu_items(vendor_id,is_available);
create table if not exists public.pickup_slots (
  id bigint generated by default as identity primary key,
  vendor_id bigint not null references public.vendors(id) on delete cascade,
  slot_date date not null, start_time time not null, end_time time not null,
  capacity integer not null default 20 check(capacity > 0),
  orders_count integer not null default 0 check(orders_count >= 0 and orders_count <= capacity),
  created_at timestamptz not null default now(), check(end_time > start_time),
  unique(vendor_id, slot_date, start_time, end_time)
);
create index if not exists pickup_slots_vendor_date_idx on public.pickup_slots(vendor_id,slot_date);
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references public.customers(id),
  vendor_id bigint not null references public.vendors(id),
  pickup_slot_id bigint references public.pickup_slots(id),
  status text not null default 'pending' check(status in ('pending','accepted','rejected','preparing','ready','collected','cancelled','no_show')),
  pickup_code text not null,
  total_amount numeric(10,2) not null check(total_amount >= 0),
  payment_status text not null default 'unpaid' check(payment_status in ('unpaid','paid','refunded','failed')),
  idempotency_key text not null unique,
  rejection_reason text, accepted_at timestamptz, ready_at timestamptz,
  collected_at timestamptz, cancelled_at timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists orders_customer_idx on public.orders(customer_id,created_at desc);
create index if not exists orders_vendor_status_idx on public.orders(vendor_id,status,created_at);
create unique index if not exists orders_active_pickup_code_idx on public.orders(vendor_id,pickup_code) where status not in ('collected','cancelled','rejected','no_show');
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  menu_item_id bigint references public.menu_items(id) on delete set null,
  name_snapshot text not null,
  price_snapshot numeric(10,2) not null check(price_snapshot >= 0),
  quantity integer not null check(quantity > 0),
  subtotal numeric(10,2) not null check(subtotal >= 0)
);
create index if not exists order_items_order_idx on public.order_items(order_id);
create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  provider text not null check(provider in ('paystack','flutterwave')),
  provider_reference text not null,
  amount numeric(10,2) not null check(amount >= 0),
  status text not null default 'pending' check(status in ('pending','success','failed','refunded')),
  raw_payload jsonb,
  created_at timestamptz not null default now(),
  unique(provider,provider_reference)
);
create index if not exists payments_order_idx on public.payments(order_id);
create table if not exists public.notifications_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  order_id bigint references public.orders(id) on delete set null,
  channel text not null check(channel in ('push','sms')),
  message text not null,
  status text not null default 'sent' check(status in ('sent','failed')),
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;
drop trigger if exists vendors_updated_at on public.vendors;
create trigger vendors_updated_at before update on public.vendors for each row execute function public.set_updated_at();
drop trigger if exists menu_items_updated_at on public.menu_items;
create trigger menu_items_updated_at before update on public.menu_items for each row execute function public.set_updated_at();
drop trigger if exists orders_updated_at on public.orders;
create trigger orders_updated_at before update on public.orders for each row execute function public.set_updated_at();

-- The RPC derives the customer from the signed-in session. Row locks serialize stock and slot reservations.
create or replace function public.place_order(
  p_vendor_id bigint, p_pickup_slot_id bigint, p_idempotency_key text, p_items jsonb
) returns bigint language plpgsql security definer set search_path = public as $$
declare
  v_customer uuid := auth.uid(); v_order_id bigint; v_item jsonb; v_menu public.menu_items%rowtype;
  v_total numeric(10,2) := 0; v_qty integer; v_code text; v_try integer := 0; v_slot public.pickup_slots%rowtype;
begin
  if v_customer is null then raise exception 'AUTH_REQUIRED'; end if;
  if p_idempotency_key is null or length(p_idempotency_key) < 12 then raise exception 'INVALID_IDEMPOTENCY_KEY'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then raise exception 'EMPTY_ORDER'; end if;
  select id into v_order_id from public.orders where idempotency_key=p_idempotency_key;
  if found then
    if exists(select 1 from public.orders where id=v_order_id and customer_id=v_customer) then return v_order_id; end if;
    raise exception 'IDEMPOTENCY_KEY_IN_USE';
  end if;
  if not exists(select 1 from public.vendors where id=p_vendor_id and status='active') then raise exception 'VENDOR_UNAVAILABLE'; end if;
  insert into public.customers(id) values(v_customer) on conflict(id) do nothing;
  if p_pickup_slot_id is not null then
    select * into v_slot from public.pickup_slots where id=p_pickup_slot_id and vendor_id=p_vendor_id and slot_date >= current_date for update;
    if not found or v_slot.orders_count >= v_slot.capacity then raise exception 'PICKUP_SLOT_FULL'; end if;
    update public.pickup_slots set orders_count=orders_count+1 where id=p_pickup_slot_id;
  end if;
  -- Create order after locking slot; a collision rolls back the slot reservation with this transaction.
  loop
    v_code := lpad(floor(random()*1000000)::text,6,'0');
    exit when not exists(select 1 from public.orders where vendor_id=p_vendor_id and pickup_code=v_code and status not in ('collected','cancelled','rejected','no_show'));
    v_try := v_try + 1; if v_try > 10 then raise exception 'PICKUP_CODE_RETRY'; end if;
  end loop;
  insert into public.orders(customer_id,vendor_id,pickup_slot_id,pickup_code,total_amount,idempotency_key)
  values(v_customer,p_vendor_id,p_pickup_slot_id,v_code,0,p_idempotency_key) returning id into v_order_id;
  for v_item in select value from jsonb_array_elements(p_items) loop
    v_qty := (v_item->>'quantity')::integer;
    if v_qty is null or v_qty < 1 or v_qty > 50 then raise exception 'INVALID_QUANTITY'; end if;
    select * into v_menu from public.menu_items where id=(v_item->>'menu_item_id')::bigint and vendor_id=p_vendor_id for update;
    if not found or not v_menu.is_available then raise exception 'ITEM_UNAVAILABLE'; end if;
    if v_menu.quantity_remaining is not null then
      if v_menu.quantity_remaining < v_qty then raise exception 'INSUFFICIENT_STOCK: %',v_menu.name; end if;
      update public.menu_items set quantity_remaining=quantity_remaining-v_qty where id=v_menu.id;
    end if;
    v_total := v_total + v_menu.price*v_qty;
    insert into public.order_items(order_id,menu_item_id,name_snapshot,price_snapshot,quantity,subtotal)
      values(v_order_id,v_menu.id,v_menu.name,v_menu.price,v_qty,v_menu.price*v_qty);
  end loop;
  update public.orders set total_amount=v_total where id=v_order_id;
  return v_order_id;
exception when unique_violation then
  select id into v_order_id from public.orders where idempotency_key=p_idempotency_key and customer_id=auth.uid();
  if v_order_id is not null then return v_order_id; end if;
  raise;
end $$;
revoke all on function public.place_order(bigint,bigint,text,jsonb) from public, anon;
grant execute on function public.place_order(bigint,bigint,text,jsonb) to authenticated;

create or replace function public.advance_order_status(p_order_id bigint,p_next_status text,p_rejection_reason text default null)
returns void language plpgsql security definer set search_path=public as $$
declare v_order public.orders%rowtype; v_vendor boolean; v_admin boolean;
begin
  select * into v_order from public.orders where id=p_order_id for update;
  if not found then raise exception 'ORDER_NOT_FOUND'; end if;
  select exists(select 1 from public.vendor_accounts where id=auth.uid() and vendor_id=v_order.vendor_id),
         exists(select 1 from public.admin_users where id=auth.uid()) into v_vendor,v_admin;
  if not v_vendor and not v_admin then raise exception 'FORBIDDEN'; end if;
  if not ((v_order.status='pending' and p_next_status in ('accepted','rejected')) or
          (v_order.status='accepted' and p_next_status in ('preparing','cancelled')) or
          (v_order.status='preparing' and p_next_status='ready') or
          (v_order.status='ready' and p_next_status in ('collected','no_show'))) then raise exception 'INVALID_STATUS_TRANSITION'; end if;
  if p_next_status='rejected' and nullif(trim(p_rejection_reason),'') is null then raise exception 'REJECTION_REASON_REQUIRED'; end if;
  update public.orders set status=p_next_status,
    rejection_reason=case when p_next_status='rejected' then trim(p_rejection_reason) else rejection_reason end,
    accepted_at=case when p_next_status='accepted' then now() else accepted_at end,
    ready_at=case when p_next_status='ready' then now() else ready_at end,
    collected_at=case when p_next_status='collected' then now() else collected_at end,
    cancelled_at=case when p_next_status='cancelled' then now() else cancelled_at end
  where id=p_order_id;
  if p_next_status in ('rejected','cancelled') then
    if v_order.pickup_slot_id is not null then
      update public.pickup_slots set orders_count=greatest(orders_count-1,0) where id=v_order.pickup_slot_id;
    end if;
    update public.menu_items mi set quantity_remaining=mi.quantity_remaining+oi.quantity
      from public.order_items oi where oi.order_id=p_order_id and oi.menu_item_id=mi.id and mi.quantity_remaining is not null;
  end if;
end $$;
revoke all on function public.advance_order_status(bigint,text,text) from public, anon;
grant execute on function public.advance_order_status(bigint,text,text) to authenticated;

create or replace function public.verify_pickup(p_order_id bigint,p_pickup_code text)
returns boolean language plpgsql security definer set search_path=public as $$
declare v_order public.orders%rowtype;
begin
  select o.* into v_order from public.orders o join public.vendor_accounts va on va.vendor_id=o.vendor_id and va.id=auth.uid() where o.id=p_order_id for update of o;
  if not found then raise exception 'ORDER_NOT_FOUND'; end if;
  if v_order.status <> 'ready' or v_order.pickup_code <> p_pickup_code then return false; end if;
  update public.orders set status='collected',collected_at=now() where id=p_order_id;
  return true;
end $$;
revoke all on function public.verify_pickup(bigint,text) from public, anon;
grant execute on function public.verify_pickup(bigint,text) to authenticated;

alter table public.vendors enable row level security;
alter table public.admin_users enable row level security;
alter table public.vendor_accounts enable row level security;
alter table public.customers enable row level security;
alter table public.menu_items enable row level security;
alter table public.pickup_slots enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.payments enable row level security;
alter table public.notifications_log enable row level security;

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.admin_users where id=auth.uid()) $$;
create or replace function public.owns_vendor(p_vendor bigint) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.vendor_accounts where id=auth.uid() and vendor_id=p_vendor) $$;

create policy vendors_public_read on public.vendors for select using(status='active' or public.owns_vendor(id) or public.is_admin());
create policy vendors_admin_insert on public.vendors for insert to authenticated with check(public.is_admin());
create policy vendors_manage on public.vendors for update to authenticated using(public.is_admin() or exists(select 1 from public.vendor_accounts where id=auth.uid() and vendor_id=vendors.id and role='owner')) with check(public.is_admin() or exists(select 1 from public.vendor_accounts where id=auth.uid() and vendor_id=vendors.id and role='owner'));
create policy admin_self_read on public.admin_users for select to authenticated using(id=auth.uid());
create policy vendor_accounts_scoped_read on public.vendor_accounts for select to authenticated using(id=auth.uid() or public.owns_vendor(vendor_id) or public.is_admin());
create policy vendor_accounts_admin_manage on public.vendor_accounts for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy customers_self_read on public.customers for select to authenticated using(id=auth.uid() or public.is_admin());
create policy customers_self_insert on public.customers for insert to authenticated with check(id=auth.uid());
create policy customers_self_update on public.customers for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy menu_public_read on public.menu_items for select using(exists(select 1 from public.vendors v where v.id=vendor_id and v.status='active') or public.owns_vendor(vendor_id) or public.is_admin());
create policy menu_vendor_manage on public.menu_items for all to authenticated using(public.owns_vendor(vendor_id) or public.is_admin()) with check(public.owns_vendor(vendor_id) or public.is_admin());
create policy slots_public_read on public.pickup_slots for select using(exists(select 1 from public.vendors v where v.id=vendor_id and v.status='active'));
create policy slots_vendor_manage on public.pickup_slots for all to authenticated using(public.owns_vendor(vendor_id) or public.is_admin()) with check(public.owns_vendor(vendor_id) or public.is_admin());
create policy orders_scoped_read on public.orders for select to authenticated using(customer_id=auth.uid() or public.owns_vendor(vendor_id) or public.is_admin());
create policy order_items_scoped_read on public.order_items for select to authenticated using(exists(select 1 from public.orders o where o.id=order_id and (o.customer_id=auth.uid() or public.owns_vendor(o.vendor_id) or public.is_admin())));
create policy payments_scoped_read on public.payments for select to authenticated using(exists(select 1 from public.orders o where o.id=order_id and (o.customer_id=auth.uid() or public.owns_vendor(o.vendor_id) or public.is_admin())));
create policy notifications_self_read on public.notifications_log for select to authenticated using(user_id=auth.uid() or public.is_admin());

-- Server-side payment webhook uses the service role; never accept payment state from the browser.

-- Realtime feeds are filtered by the SELECT policies above.
alter publication supabase_realtime add table public.vendors;
alter publication supabase_realtime add table public.menu_items;
alter publication supabase_realtime add table public.orders;
